#!/usr/bin/env node
/**
 * generateVersion.js — produce public/version.json before each build.
 *
 * The frontend polls /version.json (with a cache-busting query string) every
 * few minutes and on window focus; when the served file's `version` differs
 * from the version baked into the running bundle, an "update available"
 * banner is shown to the user.
 *
 * Why a tiny standalone JSON (not relying on Vite's __BUILD_VERSION__):
 *   - Vite's define() injects the version into the JS bundle, so it ages
 *     with the bundle. To detect a NEW deployment, we need a file the
 *     SERVER serves fresh on each deploy. version.json fits perfectly:
 *     it is regenerated by this script on every build and CDN/cache headers
 *     for plain JSON are reliably overridable to no-cache.
 *
 * Output shape (kept stable; the frontend hook reads `version` + `buildTime`):
 *   {
 *     "version": "v<base36-timestamp>",
 *     "buildTime": "<ISO 8601 string>",
 *     "commit": "<short git sha or 'unknown'>"
 *   }
 *
 * Idempotent and safe to run multiple times. Never throws — best-effort.
 */
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const PROJECT_ROOT = resolve(__dirname, '..');
const PUBLIC_DIR = resolve(PROJECT_ROOT, 'public');
const OUTPUT_FILE = resolve(PUBLIC_DIR, 'version.json');

function getGitCommit() {
  try {
    const sha = execSync('git rev-parse --short HEAD', {
      cwd: PROJECT_ROOT,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
    return sha || 'unknown';
  } catch {
    return 'unknown';
  }
}

function main() {
  const now = Date.now();
  const payload = {
    version: `v${now.toString(36)}`,
    buildTime: new Date(now).toISOString(),
    commit: getGitCommit(),
  };

  try {
    mkdirSync(PUBLIC_DIR, { recursive: true });
    writeFileSync(OUTPUT_FILE, JSON.stringify(payload, null, 2) + '\n', 'utf8');
    // eslint-disable-next-line no-console
    console.info(
      `[generateVersion] wrote ${OUTPUT_FILE} (version=${payload.version}, commit=${payload.commit})`,
    );
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn('[generateVersion] failed:', err);
    // Don't fail the build over this — the polling hook tolerates a missing file.
  }
}

main();