"""auto update

Revision ID: 81cc8afdc609
Revises: c88362216b82
Create Date: 2026-04-17 06:03:09.447279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81cc8afdc609'
down_revision: Union[str, Sequence[str], None] = 'c88362216b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_texts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text_key', sa.String(), nullable=False),
    sa.Column('text_value', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_texts_id'), 'custom_texts', ['id'], unique=False)
    op.drop_table('user_groups')
    op.alter_column('report_notes', 'is_edited',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('report_notes', 'edited_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_report_notes_parent_id'), 'report_notes', ['parent_id'], unique=False)
    op.alter_column('reports', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_roles', 'permissions',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'permissions',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'::text"),
               existing_nullable=False)
    op.alter_column('reports', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_report_notes_parent_id'), table_name='report_notes')
    op.alter_column('report_notes', 'edited_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('report_notes', 'is_edited',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_table('user_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_groups_pkey')),
    sa.UniqueConstraint('name', name=op.f('user_groups_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_custom_texts_id'), table_name='custom_texts')
    op.drop_table('custom_texts')
    # ### end Alembic commands ###