import {
  FileText,
  Clock,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Eye,
  Send,
  Archive,
  RotateCcw,
  Loader2,
  CircleDot,
  Layers,
  Wrench,
  ClipboardList,
  Shield,
  FileCheck,
  HelpCircle,
  Calculator,
  Star,
  Heart,
  Flag,
  Bell,
  Bookmark,
  Calendar,
  Camera,
  Coffee,
  Compass,
  Database,
  Download,
  Edit,
  Folder,
  Gift,
  Globe,
  Home,
  Image,
  Key,
  Link,
  Lock,
  Mail,
  Map,
  MessageCircle,
  Music,
  Package,
  Phone,
  Printer,
  Search,
  Settings,
  ShoppingCart,
  Tag,
  Trash2,
  Truck,
  Upload,
  User,
  Zap,
  Activity,
  Airplay,
  Award,
  BarChart2,
  Battery,
  BellRing,
  Bolt,
  Box,
  Briefcase,
  Bug,
  Building,
  Bus,
  Cake,
  Car,
  Check,
  Circle,
  Clipboard,
  CloudRain,
  Code,
  Cog,
  Construction,
  CreditCard,
  Droplet,
  Flame,
  Hammer,
  Headphones,
  Info,
  Lightbulb,
  ListChecks,
  MapPin,
  Megaphone,
  Monitor,
  PenTool,
  Percent,
  PieChart,
  Plug,
  Power,
  Radio,
  Rocket,
  Ruler,
  Scissors,
  Server,
  Smartphone,
  Speaker,
  Sun,
  Target,
  Terminal,
  ThumbsUp,
  Timer,
  TreePine,
  Trophy,
  Umbrella,
  Video,
  Wifi,
  Wind,
  type LucideIcon,
} from 'lucide-react';

// Complete icon map for dynamic icon rendering
export const ICON_MAP: Record<string, LucideIcon> = {
  FileText,
  Clock,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Eye,
  Send,
  Archive,
  RotateCcw,
  Loader2,
  CircleDot,
  Layers,
  Wrench,
  ClipboardList,
  Shield,
  FileCheck,
  HelpCircle,
  Calculator,
  Star,
  Heart,
  Flag,
  Bell,
  Bookmark,
  Calendar,
  Camera,
  Coffee,
  Compass,
  Database,
  Download,
  Edit,
  Folder,
  Gift,
  Globe,
  Home,
  Image,
  Key,
  Link,
  Lock,
  Mail,
  Map,
  MessageCircle,
  Music,
  Package,
  Phone,
  Printer,
  Search,
  Settings,
  ShoppingCart,
  Tag,
  Trash2,
  Truck,
  Upload,
  User,
  Zap,
  Activity,
  Airplay,
  Award,
  BarChart2,
  Battery,
  BellRing,
  Bolt,
  Box,
  Briefcase,
  Bug,
  Building,
  Bus,
  Cake,
  Car,
  Check,
  Circle,
  Clipboard,
  CloudRain,
  Code,
  Cog,
  Construction,
  CreditCard,
  Droplet,
  Flame,
  Hammer,
  Headphones,
  Info,
  Lightbulb,
  ListChecks,
  MapPin,
  Megaphone,
  Monitor,
  PenTool,
  Percent,
  PieChart,
  Plug,
  Power,
  Radio,
  Rocket,
  Ruler,
  Scissors,
  Server,
  Smartphone,
  Speaker,
  Sun,
  Target,
  Terminal,
  ThumbsUp,
  Timer,
  TreePine,
  Trophy,
  Umbrella,
  Video,
  Wifi,
  Wind,
};

// Categorized icons for the picker UI
export const ICON_CATEGORIES = [
  {
    label: 'حالات البلاغ',
    icons: ['FileText', 'CircleDot', 'Loader2', 'CheckCircle2', 'XCircle', 'Archive', 'Clock', 'Eye', 'Send', 'RotateCcw', 'AlertTriangle', 'Shield', 'FileCheck', 'ClipboardList', 'HelpCircle'],
  },
  {
    label: 'أدوات وصيانة',
    icons: ['Wrench', 'Hammer', 'Construction', 'Ruler', 'Scissors', 'PenTool', 'Cog', 'Settings', 'Plug', 'Power', 'Bolt'],
  },
  {
    label: 'تواصل',
    icons: ['Mail', 'MessageCircle', 'Phone', 'Bell', 'BellRing', 'Megaphone', 'Radio', 'Speaker', 'Headphones'],
  },
  {
    label: 'أماكن ومواقع',
    icons: ['Home', 'Building', 'Map', 'MapPin', 'Globe', 'Compass', 'Flag', 'Target'],
  },
  {
    label: 'نقل ومواصلات',
    icons: ['Car', 'Bus', 'Truck', 'Rocket', 'Airplay'],
  },
  {
    label: 'بيانات وتحليل',
    icons: ['Calculator', 'BarChart2', 'PieChart', 'Activity', 'Database', 'Server', 'Monitor', 'Code', 'Terminal'],
  },
  {
    label: 'ملفات ومستندات',
    icons: ['Folder', 'Clipboard', 'ListChecks', 'Bookmark', 'Tag', 'Download', 'Upload', 'Printer', 'Link'],
  },
  {
    label: 'أخرى',
    icons: ['Star', 'Heart', 'Zap', 'Lightbulb', 'Flame', 'Droplet', 'Sun', 'Wind', 'CloudRain', 'TreePine', 'Coffee', 'Cake', 'Gift', 'Trophy', 'Award', 'ThumbsUp', 'Timer', 'Calendar', 'Camera', 'Image', 'Video', 'Music', 'Key', 'Lock', 'User', 'Briefcase', 'ShoppingCart', 'CreditCard', 'Package', 'Box', 'Battery', 'Bug', 'Umbrella', 'Wifi', 'Smartphone', 'Percent', 'Info', 'Circle', 'Check'],
  },
];

export function getIconComponent(iconName: string | null | undefined): LucideIcon {
  if (!iconName) return CircleDot;
  return ICON_MAP[iconName] || CircleDot;
}